apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellsup-deployment
  labels:
    app: wellsup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wellsup
  template:
    metadata:
      labels:
        app: wellsup
    spec:
      initContainers:
      - name: wellsup-migrations
        image: gregoirer86/wellsup:latest
        env:
          - name: RAILS_ENV
            value: production
          - name: MYSQL_USER
            value: wellsup
          - name: MYSQL_HOST
            value: 34.159.105.113
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wellsup
                key: mysql_password
          - name: SECRET_KEY_BASE
            value: fdsjfljdkslfjdkls
        command: ["rake", "db:migrate"]
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M     
      containers:
      - name: wellsup
        image: gregoirer86/wellsup:latest
        ports:
          - containerPort: 3000
            name: "http"
        env:
          - name: RAILS_ENV
            value: production
          - name: MYSQL_USER
            value: wellsup
          - name: MYSQL_HOST
            value: 34.159.105.113
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wellsup
                key: mysql_password
          - name: SECRET_KEY_BASE
            value: fdsjfljdkslfjdkls
        resources:
          requests:
            cpu: 250m
            memory: 512M
          limits:
            cpu: 250m
            memory: 512M